site_name: "{{ username }}.github.io"
site_url: "https://{{ username }}.github.io"
repo_url: "https://github.com/{{ username }}/{{ repo_name }}"
repo_name: !ENV GITHUB_REPOSITORY
theme:
  name: material
  logo: assets/images/plex-logo.webp
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.footer
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: deep purple
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

nav:
  - Preamble: basic-info/index.md
  - What is Plex?: basic-info/what-is-plex.md
  - Is Plex safe to use?: basic-info/plex-safety.md
  - Setup:
    - Pinning Libraries: setup/pinning-libraries.md
    - Managing Newsletter Subscriptions: setup/unsubscribe-from-plex-newsletter.md
    - Disabling Online Media Sources: setup/disabling-online-media-sources.md
    - Requesting Content: setup/requesting-content.md
    - Reporting Issues: setup/reporting-issues.md
    - Changing Plex streaming quality:
      - setup/changing-stream-quality/index.md
      - iOS & Android: setup/changing-stream-quality/ios-android.md
      - tvOS (Apple TV): setup/changing-stream-quality/tv-os.md
      - Amazon Fire TV, Android TV, PlayStation 4/5, Xbox, Roku, Smart TV (LG, Samsung, VIZIO): setup/changing-stream-quality/streaming-devices.md
      - Web Browser: setup/changing-stream-quality/web-browser.md
  - FAQ:
    - What is transcoding?: faq/what-is-transcoding.md
    - Why do I need to buy the Plex app on my phone?: faq/why-do-i-to-buy-plex-app.md
    - My video won't stop buffering: faq/wont-stop-buffering.md
    - Help, I forgot my Plex password!: faq/forgot-password.md
    - How do I add items to my Plex Universal Watchlist?: faq/adding-to-universal-watchlist.md
    - Responsible Content Requesting: faq/responsible-content-requests.md
    - I requested something an hour ago but it hasn't shown up yet. Why?: faq/missing-requests.md
    - I'm having a problem with a Movie or TV Show: faq/content-issues.md
    - Content Quality and Language Options: faq/special-requests.md
    - I don't want to use this request thingy, can't I just tell you what I want?: faq/i-dont-want-to-use-overseerr.md
    - Can I share your Plex server with someone else?: faq/can-i-share-your-plex.md
    - Plex is awesome! Can I send you some money to support it?: faq/how-can-i-support-you.md
    - Why Bitrate Matters: faq/why-bitrate-matters.md
  - My Setup:
    - 3rd-party-app-info/index.md
    - 3rd Pary Applications:
      - Unraid: 3rd-party-app-info/unraid-information.md
      - Overseerr: 3rd-party-app-info/overseerr-information.md
      - Tautulli: 3rd-party-app-info/tautulli-information.md
      - Sync-Lounge: 3rd-party-app-info/sync-lounge-information.md
      - ARR Applications: 3rd-party-app-info/arr-information.md
      - qBittorrent: 3rd-party-app-info/qbittorrent-information.md
      - Plexamp: 3rd-party-app-info/plexamp-information.md
  - Useful Links: basic-info/useful-links.md

plugins:
  - search
  - mkdocs-video
  - markdownextradata: {}
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: !ENV GITHUB_REPOSITORY
      branch: !ENV GITHUB_REF_NAME
      exclude_committers:
        - "web-flow"  # GitHub web UI edits
        - "actions-user"  # GitHub Actions
        - "github-actions[bot]"  # GitHub Actions bot
      # For a repository hosted on GitHub, you can provide a token to increase the rate limit and go beyond the default 60 requests per hour per IP address.
      # The plugin will make one request per mkdocs document
      # See: https://github.com/ojacques/mkdocs-git-committers-plugin-2
      token: !ENV GITHUB_TOKEN
  - glightbox

markdown_extensions:
  - toc:
      toc_depth: 1
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: "Copyright &copy; 2025 {{ username }}"

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/{{ username }}"
      name: "{{ username }} @ Github"
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/401938150877954048
      name: Xangetzu Discord


  vars:
    username: !ENV GITHUB_REPOSITORY_OWNER
    repo_name: !ENV GITHUB_REPOSITORY
    request_url: "overseerr.ptolemi.net"
    plex_url: "plex.ptolemi.net"
    tuatulli_url: "tautulli.ptolemi.net"
    syncelounge_url: "sync-lounge.ptolemi.net"
    plex_libraries: ".anime, .movies, .television, .movies, .stand-up, .music"
    pms_server_name: "deep.thought"
    noreply_email: "noreply@example.com"

  env:
    branch: !ENV [GITHUB_REF_NAME, 'main']
    commit_sha: !ENV [commit_sha, '']  # Will be empty on main, show SHA on develop
